"use strict";

import type { Metadata } from "next";

import { Header } from "@/src/ui/components/organisms/Header/Header";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutType {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
