"use strict";

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import type { Metadata } from "next";

import { SpotiumLayout } from "@/src/ui/components/templates/SpotiumLayout";

import "../globals.scss";

export const metadata: Metadata = {
  title: "SPOTIUM 360",
  description: "Generated by create next app",
};

interface RootLayoutType {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutType) {

  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <SpotiumLayout>
        {children}
      </SpotiumLayout>
    </NextIntlClientProvider>
  );
}
